/* eslint-disable max-len */
const strings = {
  taskaty: "Taskaty",
  notifications: "Notifications",
  search: "Search",
  more: "More",
  profile: "Profile",
  projects: "Projects",
  classes: "Classes",
  logOut: "Log out",
  signUp: "Sign up",
  login: "Log in",
  firstName: "First Name",
  lastName: "Last Name",
  nextStep: "Next step",
  email: "Email",
  password: "Password",
  confirm: "Confirm",
  enterAccountInfo: "Enter your account information",
  enterLookupInfo: "Enter your lookup information",
  passwordLengthWarn: "Password must be at least 6 characters long!",
  passwordMismatchWarn: "Passwords don't match!",
  createAccount: "Create Account",
  createNewAccount: "Create new account",
  newAccountStepOne: "Step 1 - Account Information",
  newAccountStepTwo: "Step 2 - Lookup Information (Optional)",
  select: "Select",
  skills: "Skills",
  interests: "Interests",
  major: "Major",
  graduate: "Graduate",
  undergraduate: "Undergraduate",
  none: "none",
  university: "University",
  name: "Name",
  city: "City",
  work: "Work",
  company: "Company",
  country: "Country",
  academicLevel: "Academic Level",
  fieldRequired: "This field is required!",
  alreadyHaveAccount: "Already have an account?",
  landingPageWelcomeSentence: "The best way to organize your group projects!",
  landingPagefeature1Title: "Find the right team!",
  landingPagefeature1Description:
    "Taskaty provides you with many useful features that help you find the right teammates for you project!",
  landingPagefeature2Title: "Smart Suggestions!",
  landingPagefeature2Description:
    "Can’t decide which users can be a good fit to work on your project? Don’t worry! Taskaty will give you a list of suggested users based on the description of your project.",
  landingPagefeature3Title: "Organize your tasks!",
  landingPagefeature3Description:
    "Taskaty provides you with a task board for your team to organize and keep track of your tasks and their status!",
  landingPagefeature4Title: "Organize your files!",
  landingPagefeature4Description:
    "Taskaty organizes your files and uploads in a very user-friendly way, that will ensure that the user is always aware of the latest version of each file. ",
  landingPageSignUpTitle: "And much more!",
  landingPageSignUpDescription:
    "Explore Taskaty and its full potential by signing up for free today!"
};

export default strings;
